#!/usr/bin/env python3
"""Repository-local entrypoint for cleaning duplicated CLI evaluation inputs."""

from evaluation.cli_clear import main


if __name__ == "__main__":
    raise SystemExit(main())
